name: humor
channels:
    - pytorch
dependencies:
    - python=3.6
    - pytorch=1.4.0
    - nltk=3.2.5
    - numpy
    - scikit-learn=0.19.1
    - pandas=0.23.0
    - pip
    - pip:
        - transformers==2.6.0
        - torchtext==0.5.0
        - allennlp==0.9.0
        - spacy==2.1