name: humor
channels:
    - pytorch
dependencies:
    - python=3.6
    - pytorch=1.4.0
    - torchtext==0.5.0
    - numpy=1.16.4
    - pandas=1.0.3
    - scikit-learn=0.22.2
    - pip
    - pip:
        - transformers==2.6.0
        - allennlp==0.9.0
        - spacy==2.1
        - nltk==3.4.5
        - tensorboardX==1.9
